[package]
name = "solana_contract"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.16"
solana-sdk = "1.16"
solana-program = "1.16"
spl-token = "3.5.0"
spl-associated-token-account = "1.1.3"
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
anyhow = "1.0"
thiserror = "1.0"